### ISSUE TITLE
Only runs with some versions of gradio

### ISSUE THREAD

**Issue by marcusmohr** [aihpi/ragsst#4]
I had problems getting the tool to work. After some tests it only seems to work with some versions of the gradio library.

With gradio **v5.3.0** I got the following error:
```
Traceback (most recent call last):
  File "/home/user/ragsst/app.py", line 14, in <module>
    main()
  File "/home/user/ragsst/app.py", line 9, in main
    mpragst = make_interface(ragsst)
  File "/home/user/ragsst/ragsst/interface.py", line 63, in make_interface
    with gr.ChatInterface(
TypeError: ChatInterface.__init__() got an unexpected keyword argument 'undo_btn'
```

With gradio **v4.19.2** instead I got the following error:
```
Traceback (most recent call last):
  File "/home/user/ragsst/app.py", line 14, in <module>
    main()
  File "/home/user/ragsst/app.py", line 9, in main
    mpragst = make_interface(ragsst)
  File "/home/user/ragsst/ragsst/interface.py", line 22, in make_interface
    rag_query_ui = gr.Interface(
  File "/home/user/ragsst/.myvenv/lib/python3.10/site-packages/gradio/interface.py", line 348, in __init__
    raise ValueError(
ValueError: The clear_btn parameter must be a gr.Button or string, not <class 'NoneType'>
```

Now with gradio **v4.44.1** it works! I would therefore suggest at least adapting the requirements.

**Comment by felixboelter** [comment]
Requirements updated to **v4.44.1**. See #5
